# Generated by Django 6.0.1 on 2026-02-01 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
        ('materials', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField()),
                ('voucher_no', models.CharField(blank=True, default='', max_length=64)),
                ('customer_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Company', 'Company')], default='Commercial', max_length=16)),
                ('party_name', models.CharField(blank=True, default='', max_length=160)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=160)),
                ('driver_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=8)),
                ('packing', models.CharField(blank=True, default='', max_length=120)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('print_type', models.CharField(choices=[('DOS Print', 'DOS Print'), ('Win Print', 'Win Print')], default='Win Print', max_length=16)),
                ('in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('out_at', models.DateTimeField(blank=True, null=True)),
                ('weight1', models.PositiveIntegerField(default=0)),
                ('weight2', models.PositiveIntegerField(default=0)),
                ('net_weight', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Error', 'Error')], default='Pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slips', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slips', to='customers.customer')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slips', to='materials.material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_slips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'branch', 'status'], name='slips_slip_company_30d451_idx'), models.Index(fields=['company', 'serial_no'], name='slips_slip_company_753e84_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'serial_no'), name='uniq_serial_per_company_slips')],
            },
        ),
    ]
