# Generated by Django 6.0.1 on 2026-02-01 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(max_length=32)),
                ('type', models.CharField(default='Truck 10-Wheeler', max_length=64)),
                ('driver', models.CharField(blank=True, default='', max_length=128)),
                ('capacity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='companies.company')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'branch', 'reg'], name='vehicles_ve_company_4311b6_idx'), models.Index(fields=['company', 'branch', 'driver'], name='vehicles_ve_company_782c41_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'reg'), name='uniq_vehicle_reg_per_company')],
            },
        ),
    ]
