# Generated by Django 6.0.1 on 2026-02-01 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9+() \\-]{7,32}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('customer_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Logistics', 'Logistics'), ('Construction', 'Construction'), ('Agriculture', 'Agriculture'), ('Individual', 'Individual')], default='Commercial', max_length=32)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Overdue', 'Overdue'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'branch', 'name'], name='customers_c_company_765c12_idx'), models.Index(fields=['company', 'branch', 'phone'], name='customers_c_company_d58f1b_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_customer_code_per_company'), models.UniqueConstraint(fields=('company', 'phone'), name='uniq_customer_phone_per_company')],
            },
        ),
    ]
