# Generated by Django 6.0.1 on 2026-04-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_manager_name_branch_company_branch_manager'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='baud_rate',
            field=models.PositiveIntegerField(default=9600, help_text='Common: 9600, 19200, 38400'),
        ),
        migrations.AddField(
            model_name='device',
            name='com_port',
            field=models.CharField(blank=True, default='', help_text='e.g., COM3, /dev/ttyUSB0', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='connection_type',
            field=models.CharField(choices=[('Serial (COM Port)', 'Serial (COM Port)'), ('TCP/IP (Network)', 'TCP/IP (Network)'), ('USB', 'USB'), ('Bluetooth', 'Bluetooth')], default='Serial (COM Port)', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current weight reading in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='data_bits',
            field=models.PositiveIntegerField(default=8, help_text='7 or 8'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Weight Indicator', 'Weight Indicator'), ('Thermal Printer', 'Thermal Printer'), ('Indicator + Printer', 'Indicator + Printer')], default='Weight Indicator', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='last_calibration_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='paper_size',
            field=models.CharField(default='80mm', help_text='80mm or 58mm', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='parity',
            field=models.CharField(default='N', help_text='N=None, E=Even, O=Odd', max_length=1),
        ),
        migrations.AddField(
            model_name='device',
            name='printer_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.CharField(choices=[('Modbus RTU', 'Modbus RTU'), ('Continuous Stream', 'Continuous Stream'), ('ESC/POS (Printer)', 'ESC/POS (Printer)'), ('Custom Protocol', 'Custom Protocol')], default='Continuous Stream', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='stop_bits',
            field=models.PositiveIntegerField(default=1, help_text='1 or 2'),
        ),
        migrations.AddField(
            model_name='device',
            name='uptime_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='weight_unit',
            field=models.CharField(default='kg', help_text='kg, lb, g', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance'), ('Error', 'Error')], default='Offline', max_length=20),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['branch', 'status'], name='devices_dev_branch__35239d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type', 'is_active'], name='devices_dev_device__96d51f_idx'),
        ),
    ]
