# Generated by Django 6.0.1 on 2026-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
