# Generated by Django 6.0.1 on 2026-02-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('material_type', models.CharField(choices=[('Bulk', 'Bulk'), ('Solid', 'Solid'), ('Liquid', 'Liquid')], default='Bulk', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='companies.company')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'branch', 'name'], name='materials_m_company_14dc45_idx'), models.Index(fields=['company', 'branch', 'code'], name='materials_m_company_c4c263_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_material_name_per_company'), models.UniqueConstraint(fields=('company', 'code'), name='uniq_material_code_per_company')],
            },
        ),
    ]
