# Generated by Django 6.0.1 on 2026-02-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_manager_name_branch_company_branch_manager'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='material',
            name='uniq_material_name_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='material',
            name='uniq_material_code_per_company',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='materials_m_company_14dc45_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='materials_m_company_c4c263_idx',
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['branch', 'name'], name='materials_m_branch__d04ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['branch', 'code'], name='materials_m_branch__9f0d25_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_material_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='uniq_material_code_per_branch'),
        ),
        migrations.RemoveField(
            model_name='material',
            name='company',
        ),
    ]
